device: "cuda"
seed: 3

run_name: "default_colab"
sst_dir: "/tmp/sst"
cloud_dir: "/tmp/cloud"
fnd_sst_path: "mur25_2012_foundation.nc"

epochs: 10

var: ssta
use_triplet: false
use_loc: false

# Model must be the ResNet backbone autoencoder
model:
  n_enc_layers: 3
  dec_data_chs: [384, 256, 64]
  dec_mask_chs: [128, 64, 32]

optim:
  name: Adam
  lr: 0.0001

scheduler:
  name: CosineAnnealingLR
  args:
    - ${epochs}
  kwargs:

train:
  name: SSTDataset
  kwargs:
    K: 1
    preload: false
    return_coord: ${use_loc}
    fnd_sst_path: ${fnd_sst_path}
    cloud_ratio_range: [0.4, 0.8]
  loader:
    batch_size: 32
    pin_memory: true
    num_workers: 2
    prefetch_factor: 6
    shuffle: true

# Val dataset is always SSTDataset regardless of the train dataset
val:
  name: SSTDataset
  kwargs:
    K: 1
    preload: false
    return_coord: ${use_loc}
    fnd_sst_path: ${fnd_sst_path}
    cloud_ratio_range: ${train.kwargs.cloud_ratio_range}
  loader:
    batch_size: 32
    pin_memory: true
    num_workers: 2
    prefetch_factor: 6
    shuffle: false

loss:
  sst_loss:
    name: MaskedLoss
    weight: 1
  mask_loss:
    name: MaskBCELoss
    weight: 0.1
