device: "cpu"
seed: 3

sst_dir: "/Users/ellin/data/sst"
cloud_dir: "/Users/ellin/data/cloud"
fnd_sst_path: "/Users/ellin/data/mur25_2012_foundation.nc"
save_dir: "/Users/ellin/sat_sst_saves"

epochs: 10
save_epoch: 5
val_epoch: 1

wandb:
  entity: ellinzh
  project: sat_sst
  name: test_pretrained_0911_1047

pretrained_weights_path: /Users/ellin/Downloads/vanilla_4layers_0910_1240/training_ckpt.tar
var: ssta
use_triplet: false
use_loc: false

# Model must be the ResNet backbone autoencoder
model:
  n_enc_layers: 4
  dec_data_chs: [896, 512, 128, 64]
  dec_mask_chs: [128, 96, 64, 32]

optim:
  name: Adam
  lr: 0.0001

scheduler:
  name: CosineAnnealingLR
  args:
    - ${epochs}
  kwargs:

train:
  name: SSTDataset
  kwargs:
    K: 1
    preload: false
    return_coord: ${use_loc}
    fnd_sst_path: ${fnd_sst_path}
    cloud_ratio_range: [0.4, 0.8]
  loader:
    batch_size: 32
    pin_memory: false
    num_workers: 0
    shuffle: true

# Val dataset is always SSTDataset regardless of the train dataset
val:
  name: SSTDataset
  kwargs:
    K: 1
    preload: false
    return_coord: ${use_loc}
    fnd_sst_path: ${fnd_sst_path}
    cloud_ratio_range: ${train.kwargs.cloud_ratio_range}
  loader:
    batch_size: 32
    pin_memory: false
    num_workers: 0
    shuffle: false

loss:
  sst_loss:
    name: GradWeightedLoss
    weight: 1
  ssim_loss:
    name: SSIMLoss
    weight: 1
  mask_loss:
    name: MaskBCELoss
    weight: 0.1

val_loss:
  sst_loss:
    name: MaskedLoss
  ssim_loss:
    name: SSIMLoss
